server:
  address: 0.0.0.0
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    # ✅ Disable self-preservation in dev so Eureka doesn't panic
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    renewal-percent-threshold: 0.49

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
