server:
  port: 8081

spring:
  application:
    name: farm-service

  datasource:
    url: jdbc:postgresql://postgres:5432/farmdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true           # Ensure registry fetching enabled
    register-with-eureka: true    # Enable service registration
  instance:
    prefer-ip-address: true
    hostname: farm-service
    health-check-url-path: /actuator/health
    metadata-map:
      instanceId: farm-service:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
